"""criando tabelas animal, cupom_resgatado, cupom, escola e usuario

Revision ID: 1fc8531267f0
Revises: 
Create Date: 2024-10-10 18:24:39.618237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc8531267f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_comum', sa.String(length=150), nullable=False),
    sa.Column('nome_cientifico', sa.String(length=150), nullable=False),
    sa.Column('habitat', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_animal'),
    sa.UniqueConstraint('nome_cientifico', name='ck_nome_cientifico_unico')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=False),
    sa.Column('endereco', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('celular', sa.String(length=30), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_escola')
    )
    op.create_table('cupom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=8), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('data_validade', sa.DateTime(), server_default=sa.text("NOW() + INTERVAL '7 days'"), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], name='fk_cupom_animal'),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name='fk_cupom_escola'),
    sa.PrimaryKeyConstraint('id', name='pk_cupom'),
    sa.UniqueConstraint('codigo', name='ck_codigo_unico')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('data_nascimento', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.SmallInteger(), nullable=False, comment='1 = Administrador, 2 = Responsável, 3 = Aluno'),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('tipo IN (1, 2, 3)', name='check_tipo'),
    sa.ForeignKeyConstraint(['escola_id'], ['escola.id'], name='fk_usuario_escola'),
    sa.PrimaryKeyConstraint('id', name='pk_usuario'),
    sa.UniqueConstraint('email', name='ck_email_unico')
    )
    op.create_table('cupom_resgatado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('cupom_id', sa.Integer(), nullable=False),
    sa.Column('data_resgate', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupom.id'], name='fk_cupom_resgatado_cupom'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name='fk_cupom_resgatado_usuario'),
    sa.PrimaryKeyConstraint('id', name='pk_cupom_resgatado')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cupom_resgatado')
    op.drop_table('usuario')
    op.drop_table('cupom')
    op.drop_table('escola')
    op.drop_table('animal')
    # ### end Alembic commands ###
