"""adicionado a coluna data_cadastro na tabela cupom

Revision ID: b56cddb55ee1
Revises: 1fc8531267f0
Create Date: 2024-10-15 18:59:47.383180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b56cddb55ee1'
down_revision: Union[str, None] = '1fc8531267f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cupom', sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cupom', 'data_cadastro')
    # ### end Alembic commands ###
